apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: print-readme
spec:
  steps:
    - name: print-readme-exec
      image: quay.io/ibmgaragecloud/alpine-curl
      script: |
        cat dir-with-readme/README.md
  workspaces:
    - name: dir-with-readme
